server:
  port: 8502

spring:
  application:
    name: ticket-service
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Genius33Frozen
  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    username: haydikodlayalim
    password: haydikodlayalim
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/