version: '3.1'

services:
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'

  msrabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=haydikodlayalim
      - RABBITMQ_DEFAULT_PASS=haydikodlayalim

